- name: Install nginx
  hosts: ec2
  become: true
  remote_user: ubuntu
  roles:
    - {role: nginx,
     nginx_http_params: ["sendfile on", "access_log /var/log/nginx/access.log"]
                          }